version: '3.8'

services:
  mongo:
    image: docker.io/zcube/bitnami-compat-mongodb:5.0
    container_name: fastfood-bff-mongo
    ports:
      - "27017:27017"
    networks:
      - fastfood-bff-network
    environment:
      MONGODB_USERNAME: common_user
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: fastfood
      MONGODB_ROOT_PASSWORD: rootpassword
    volumes:
      - 'mongodb_data:/fastfood'
  sqs:
    image: softwaremill/elasticmq:1.4.2
    container_name: fastfood-bff-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./sqs-compose.conf:/opt/elasticmq.conf
      - sqs_data:/data/db
    networks:
      - fastfood-bff-network
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
      POSTGRES_USER: "fastfood"
      POSTGRES_DB: fastfood-customer
    networks:
      - fastfood-bff-network
    volumes:
      - ./db/1-create-customer-table.sql:/docker-entrypoint-initdb.d/1-create-customer-table.sql
    ports:
      - "5432:5432"

volumes:
  mongodb_data:
    driver: local
  sqs_data:
    driver: local

networks:
  fastfood-bff-network:
    driver: bridge