spring:
  application:
    name: fastfood-bff

grpc:
  server:
    health-service-enabled: true
  client:
    order-api:
      address: dns:///fastfood-order:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    tracking-api:
      address: dns:///fastfood-tracking:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    product-api:
      address: dns:///fastfood-product:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

management:
  health:
    probes:
      enabled: true
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"