spring:
  application:
    name: fastfood-bff

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_PROVIDER_ISSUER_URI:http://localhost:7777/auth/realms/vodafone}
          #issuer-uri: ${OIDC_PROVIDER_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_YUMMjIAXc/.well-known/openid-configuration}
grpc:
  server:
    health-service-enabled: true
  client:
    order-api:
      address: dns:///fastfood-order:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    tracking-api:
      address: dns:///fastfood-tracking:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    product-api:
      address: dns:///fastfood-product:9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

management:
  health:
    probes:
      enabled: true
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"