grpc:
  client:
    order-api:
      enabled: true
      address: static://localhost:9091
    tracking-api:
      enabled: true
      address: static://localhost:9093
    product-api:
      enabled: true
      address: static://localhost:9092
    customer-api:
      enabled: true
      address: dns:///localhost:9096

server:
  port: 8080