name: 'Publish package'
description: 'Publishes packages to aws'
inputs:
  AWS_SECRET_ACCESS_KEY:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_REGION:
    required: false
    default: "eu-east-1"
  CLUSTER_NAME:
    required: true
  VALUES_PATH:
    required: true
  RELEASE_NAME:
    required: true

runs:
  using: 'ubuntu-latest'
  steps:
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.9
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}
        cluster-name: ${{ inputs.CLUSTER_NAME }}
        config-files: ${{ inputs.VALUES_PATH }}
        chart-path: charts/
        namespace: default
        name: ${{ inputs.RELEASE_NAME }}
        #values: key1=value1,key2=value2
